### ISSUE TITLE
iTunes 10.0.1 compatibility

### ISSUE THREAD

**Issue by kawazoe** [wilg/harmonic#4]
Lyrics are always (null) when using iTunes 10.0.1

**Comment by MattiSG** [comment]
Done  :)

**Comment by Legume** [comment]
By done do you mean it's fixed?  I've downloaded the latest version (which lists its modification date as September 10, 2010) and I am still have the always null problem.

**Comment by MattiSG** [comment]
It's fixed in my repo, supapuerco has not pulled the changes…
Please download the latest version (.wdgt.zip) from my downloads page: http://github.com/MattiSG/harmonic/downloads  :)

**Comment by Legume** [comment]
Got it.  Thanks Matt.
